
path: r"C:\RWTH Aachen University\Projects\Object Detection\OIDv4_ToolKit\OID\Dataset\train\Car"  # dataset root dir
train: "Yolo_labels"  # train images (relative to 'path')
val: "Yolo_labels"  # val images (relative to 'path')

# Classes
names:
  0: Car