path: '/content/drive/MyDrive/Object Detection/Car Detection/datasets/Car' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val # val images (relative to 'path')

# Classes
names:
  0: Car